#
# Makefile for ip proxy library
#

INTERNALLIB=	yes
LIB=		socket
SRCS=		reply_collector.c socket_connect.c socket_handle.c
INCS=		reply_collector.h socket_connect.h socket_handle.h

.include <bsd.lib.mk>
