#
# Makefile for ip proxy library
#

INTERNALLIB=	yes
LIB=		command
SRCS=		bhyve_command.c command_sender.c vm_info.c vm_info_map.c
INCS=		bhyve_command.h command_sender.h vm_info.h

.include <bsd.lib.mk>
